let un1 = localStorage.getItem("z1");
let un2 = localStorage.getItem("z2");
let un3 = localStorage.getItem("z3");
let un4 = localStorage.getItem("z4");
b1 = document.getElementById("sp1");
b1.innerHTML = un1;
b2 = document.getElementById("sp2");
b2.innerHTML = un2;
b3 = document.getElementById("sp3");
b3.innerHTML = un3;
b4 = document.getElementById("sp4");
b4.innerHTML = un4;
b5 = document.getElementById("sp5");
b5.innerHTML =  parseInt(un1)+parseInt(un2)+parseInt(un3)+parseInt(un4);
b6 = document.getElementById("sp6");
b6.innerHTML =  parseInt(un1)+parseInt(un2)+parseInt(un3)+parseInt(un4);
console.log(un1);
console.log(un2);
console.log(un3);
console.log(un4);